Adding more fields to log
NCSU-High-Powered-Rocketry-Club/AirbrakesV2 pull request #100
Opened 2024-11-21 22:01 UTC by JacksonElia

Why not log even more data? With this PR we need to log:
- [ ] Make it correctly log extension
- [ ] Log Convergence Parameters
- [ ] Log Queue sizes
- [ ] Log the first timestamp/packet which airbrakes.update() runs with

2024-11-22 05:05 UTC, harshil21 commented
I would argue that after #99 we don't need to log queue sizes anymore.

2024-11-22 17:01 UTC, wlsanderson commented
I still think we should tbh. Theres no reason not to. It definitely helps with debugging and finding where performance issues happen, and it's one of the fields where you cant go back in post-processing and find it out then.

2024-11-22 17:05 UTC, JacksonElia commented
I agree with will. If for some reason in the future they do exceed 15, we wouldn't know that easily,

2024-11-22 17:06 UTC, wlsanderson commented
i mean whats one more column on the log file. Gotta use the whole 128gb if we have 128gb

2024-11-22 17:15 UTC, harshil21 commented
alright, it could be ever so slightly more overhead but it's probably worth it

2024-11-25 03:48 UTC, harshil21 commented
Changes:

- All packets are now in a separate folder
- `DebugPacket` is only logged for the first packet processed, so that way we know which is the first packet the batch was, and also saves some space since those fields would be repeated for that batch anyway.

2024-11-25 20:37 UTC, wlsanderson reviewed
I feel like the debug packet is just not an elegant solution to this issue. While I can see the purpose of logging at the start of each set of packets, this seems like it adds a lot more complexity to the issue. Passing the DebugPacket into a LoggedDataPacket just doesn't really sit right with me lol. I think just having these values logged every line (even if they don't update) is a cleaner solution, and arguably easier to do post-processing with.

2024-11-25 20:55 UTC, harshil21 commented
Well we do have a lot of fields to log and the `log()` method is just getting too crowded. We are probably going to have more fields we would want to log in the future.

If we log these for the entire batch, then we would need another field to know which packet was the first one in the batch. 

I guess it's now up to @JacksonElia to break the tie.

2024-11-27 22:24 UTC, JacksonElia commented
I agree with Will here, I don't think I like the DebugDataPacket. Though because we have multiple fields we are logging from the apogee predictor, I would be fine with an apogee_prediction_data_packets. As for the queue sizes, I think they should be logged separately/individually.

After thinking about this a lot though, I think that the cleanest solution could eventually be using **kwargs when logging. Maybe I'll add it eventually.

2024-11-28 00:12 UTC, harshil21 commented
> I would be fine with an apogee_prediction_data_packets.

So another data packet class but would only contain things from that process? I can get behind that. How do you want to send the packets from that process to the main process? Do you want to include `predicted_apogee` in that too? Another Queue?

> After thinking about this a lot though, I think that the cleanest solution could eventually be using **kwargs when logging. 

Where? Some more details would be nice

2025-01-07 16:06 UTC, JacksonElia commented
Me and will talked about it a lot, we agree with the need of some data packet like debug data packet.

We want to emphasize categorizing information with data packets, and paying attention to what "owns" a data packet, so we're gonna make a data packet for apogee predictor and for the context (this will be like your debug data packet). We also will probably make a servo data packet because we're gonna have the encoder info.

2025-01-09 04:22 UTC, JacksonElia commented
Okay I think now all is left is actually logging the ContextPacket and the ApogeePredictorPackets
@harshil21 if you want to do it, go for it, if not I'll work on it soon. Lmk what you think of my implementation with the queue stuff

2025-01-09 15:13 UTC, wlsanderson reviewed
We should probably include state in the Context Packet, as well as either making a servo packet (with extension and eventually encoder) or just put servo extension into Context Packet as well

2025-01-09 15:13 UTC, wlsanderson commented on airbrakes/airbrakes.py
> +        self.debug_packet: ContextPacket | None = None
do we plan to just keep it named debug_packet?

2025-01-09 17:17 UTC, JacksonElia commented on airbrakes/airbrakes.py
> +        self.debug_packet: ContextPacket | None = None
no that will be changed

2025-01-09 17:18 UTC, JacksonElia commented
Yes state should be in ContextPacket and we can make a ServoPacket

2025-01-10 04:26 UTC, harshil21 requested changes
core logic looks good.

2025-01-10 04:26 UTC, harshil21 commented on airbrakes/data_handling/apogee_predictor.py
> +        ]
use `queue.get_many()`

2025-01-10 04:26 UTC, harshil21 commented on airbrakes/data_handling/apogee_predictor.py
> +                apogee = -1
let's use `self.apogee` and `self.curve_coefficients` and initialize them to `None`

2025-01-10 04:26 UTC, harshil21 commented on airbrakes/data_handling/apogee_predictor.py
> +                    self._send_to_main_process(curve_coefficients)
```suggestion
```
bye

2025-01-10 04:26 UTC, harshil21 commented on airbrakes/data_handling/apogee_predictor.py
> +                        uncertainty_threshold_2=self.uncertainty_threshold_2.value,
```suggestion
                        uncertainty_threshold_1=self.uncertainty_threshold_1,
                        uncertainty_threshold_2=self.uncertainty_threshold_2,
```

2025-01-10 04:26 UTC, harshil21 commented on airbrakes/data_handling/apogee_predictor.py
> +    def queue_size(self) -> int:
name is ambiguous since we now have 2 queues

2025-01-10 04:26 UTC, harshil21 commented on airbrakes/airbrakes.py
> +            self.apogee_predictor_data_packets = apogee_predictor_data_packets
let's assign `self.apogee..` to `None` when no packets were fetched, so we only get them for CoastState

2025-01-10 04:26 UTC, harshil21 commented on airbrakes/data_handling/logger.py
> +                apogee_predictor_data_packet_dict: dict[str, float] = to_builtins(
Need a comment specifying that we only care about the last apogee predictor packet

2025-01-10 04:26 UTC, harshil21 commented on airbrakes/data_handling/logger.py
>      def _prepare_log_dict(
this function needs to convert the state name to state letter in the context data packet

2025-01-10 04:26 UTC, harshil21 commented on airbrakes/data_handling/packets/logger_data_packet.py
> +    # fields in a DebugPacket:
```suggestion
    # fields in a ApogeePredictionPacket:
```

2025-01-10 04:26 UTC, harshil21 commented on airbrakes/data_handling/packets/logger_data_packet.py
> +    packets_in_imu_queue: str | None
all these need to be changed

2025-01-10 04:26 UTC, harshil21 commented on airbrakes/data_handling/packets/logger_data_packet.py
> +    extension: str
need to add the other ContextPacket fields & add a comment saying that it is of a ContextPacket

2025-01-10 06:31 UTC, JacksonElia commented on airbrakes/data_handling/apogee_predictor.py
> +
bro I have no idea i don't remember making this code

2025-01-12 06:42 UTC, harshil21 commented
One major thing I found - 

https://github.com/NCSU-High-Powered-Rocketry-Club/AirbrakesV2/blob/be90a4e1a791e63b85fe58e5392755552d87809a/airbrakes/data_handling/logger.py#L173-L180

Since this is asynchronous, we cannot assume that the length of `apogee_predictor_data_packets` is less than the `imu_data_packets` passed to `log()`. Which means there is a super tiny possibility that we don't log all the apogee predictor packets and stop prematurely. 

My recommended fix would be to use another queue to which we add the packets, and then `log()` automatically fetches from it if it's not empty. 

However, I'm first going to test a lot if this would even happen, since we get one ApogeePredictorDataPacket for every 10 ProcessedDataPackets, and we fetch a maximum of 5 EstimatedDataPackets per iteration.

2025-01-13 00:44 UTC, harshil21 approved these changes
LGTM. The issue I mentioned does not happen even on 1x speed.

2025-01-13 04:33 UTC, JacksonElia commented
@harshil21 that is definitely a good thing to keep in mind, but because of this line in apogee predictor
```py
if len(self._accelerations) - last_run_length >= APOGEE_PREDICTION_MIN_PACKETS:
```

the apogee predictor packets should never out pace the imu packets. Also side note, I think we should consider lowering this to like 5 because even 10 seems a little high (especially considering that we have finally ordered a pi 5).

2025-01-13 04:36 UTC, JacksonElia commented on airbrakes/data_handling/packets/logger_data_packet.py
> +    set_extension: str | None
wait actually shouldn't this be a float or are we logging the enum?

2025-01-13 04:38 UTC, harshil21 commented
I'm fine with that. Lowering that would make no meaningful difference in convergence time, nor would it affect performance anyway.

We could do it in another PR.

2025-01-13 04:41 UTC, harshil21 commented on airbrakes/data_handling/packets/logger_data_packet.py
> +    set_extension: str | None
we are logging the value, but it will be a string, because if it is a float, our method of truncation will force it to become something like `0.40000000` (8 decimal places truncation)

2025-01-13 04:42 UTC, JacksonElia commented on airbrakes/airbrakes.py
> +            # Cache the apogee value so we don't have to keep recalculating it
Why is this necessary? Accessing the list isn't expensive and I don't get what you mean by recalculating. Also I don't like this being a property here, if we make it a property I feel like apogee predictor should own it

2025-01-13 04:42 UTC, JacksonElia commented on airbrakes/data_handling/packets/context_data_packet.py
> +    state_letter: Literal["S", "M", "C", "F", "L"]
clean

2025-01-13 04:44 UTC, JacksonElia commented on airbrakes/data_handling/apogee_predictor.py
> +                max_size_bytes=BUFFER_SIZE_IN_BYTES
do we want this to be the same buffer size? also did we put much thought into what the buffer size should be or is it just kinda arbitrary? Not saying thats a bad thing, just curious

2025-01-13 04:46 UTC, JacksonElia commented on airbrakes/data_handling/logger.py
> +                    apogee_predictor_data_packets.pop(0), enc_hook=Logger._convert_unknown_type
wait what does this do

2025-01-13 04:51 UTC, harshil21 commented on airbrakes/airbrakes.py
> +            # Cache the apogee value so we don't have to keep recalculating it
This isn't about it being expensive to access, but has two purposes:

1) Provides a clean way for the state machine to query for the apogee
2) `self.apogee_predictor_data_packets` will be an empty list when our loop is only running with a `RawDataPacket`. This means that we'll have an IndexError.
3) Because of 2), we need to store the previous received predicted apogee value. That's what I meant by caching it. 

I'll update the comment to reflect why this is done the way it is.

> property I feel like apogee predictor should own it

fair concern. However this means we also need another init variable in `ApogeePredictor`, and mind you we already have one called `self._apogee`, but that is only referenceable in the other process. So do you want a new name for this or keep in it AirbrakesContext?

2025-01-13 04:52 UTC, harshil21 commented on airbrakes/data_handling/logger.py
> +                    apogee_predictor_data_packets.pop(0), enc_hook=Logger._convert_unknown_type
converts numpy floats to regular floats

2025-01-13 04:55 UTC, JacksonElia commented on airbrakes/data_handling/packets/logger_data_packet.py
> +    set_extension: str | None
idk if I like that but I'll address this later if I feel like

2025-01-13 04:55 UTC, harshil21 commented on airbrakes/data_handling/apogee_predictor.py
> +                max_size_bytes=BUFFER_SIZE_IN_BYTES
The default buffer size is a bit too small for our packets specially when we have like over a 100 of them. I remember it completely clogging up the logger queue and it was hard to know why (there was no error either).

The buffer size is big enough to accommodate 1000s of packets

2025-01-13 04:56 UTC, JacksonElia commented on airbrakes/airbrakes.py
> +            # Cache the apogee value so we don't have to keep recalculating it
wait i'll just push it I got an idea gimme one min

2025-01-13 04:57 UTC, JacksonElia commented on airbrakes/airbrakes.py
> +            # Cache the apogee value so we don't have to keep recalculating it
lol this is going back on what we said a couple days ago but I'll explain

2025-01-13 05:15 UTC, JacksonElia commented on airbrakes/data_handling/logger.py
> +                    apogee_predictor_data_packets.pop(0), enc_hook=Logger._convert_unknown_type
nice

2025-01-16 17:00 UTC, wlsanderson commented on tests/test_apogee_predictor.py
>          assert 0.0 in unique_apogees
I'm pretty sure this test should be removed. When we send packets to the apogee predictor, we shouldn't get a zero apogee because the first group of packets in this test causes it to converge, and then that same group of packets will predict apogee with the lookup table.

2025-01-16 21:49 UTC, harshil21 reviewed
inital re-review

2025-01-16 21:49 UTC, harshil21 commented on airbrakes/data_handling/apogee_predictor.py
> +                total_packets.extend(new_packets)
I don't think we need to do a while loop here, we'll only ever practically get ~<2 packets per iteration

2025-01-16 22:00 UTC, merged